### ISSUE TITLE
Images with captions should not have an alt text.

### ISSUE THREAD

**Issue by 42ndTowel** [isunjn/serene#1]
According to [this source](https://www.csun.edu/universal-design-center/best-practices-accessible-images#a3), captions already provide a description of the image, and the `alt` attribute should thus be set to `null` (i.e., `alt=""`).

Currently, the [documentation](https://github.com/isunjn/serene/wiki/English-Docs#shortcodes) recommends adding the alt text regardless of whether or not a caption text is supplied.

**Comment by isunjn** [comment]
I don't think so. There is no such suggestion on [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure) and `alt` and `caption` serve different purposes, as explained in this [post](https://thoughtbot.com/blog/alt-vs-figcaption).

**Comment by 42ndTowel** [comment]
Fair enough. 👍🏿
