### ISSUE TITLE
Issue with English Docs

### ISSUE THREAD

**Issue by tarunjana** [isunjn/serene#2]
First of all, Thank you so much for this amazing theme.

I was trying to use this theme as a git submodule. But a minor typo is creating issues.

The command as written in the docs is: `git submodule add https://github.com/isunjn/serene.git theme/serene`

But the [official docs](https://www.getzola.org/documentation/themes/installing-and-using-themes/) of Zola instructs to install a theme in the `themes` directory.

So the correct command to use the theme as a git submodule should be: `git submodule add https://github.com/isunjn/serene.git themes/serene`

**Comment by isunjn** [comment]
Fixed, Thank you!
