### ISSUE TITLE
Add generic page.html ? 

### ISSUE THREAD

**Issue by slashformotion** [isunjn/serene#21]
I add to modify your theme to make it work with generic content, would you be open to introducing modifications that could allow the creation of pages that are not projects or blog posts ?

**Comment by isunjn** [comment]
what do you mean "generic content"?

**Comment by slashformotion** [comment]
I would like to be able to have pages with pictures on them (i am a photograph on my spare time), it would be great to be able to create generic sections and have a page template that is not a post.

**Comment by isunjn** [comment]
I don't think add a generic page.html directly to the theme is a good idea.

People will have their specific customization needs, a generic section just can't fit for everyone and would be useless for those who can't write css.

I'm considering to add some common pages, like 'about', 'bookmarks', 'friends', mabe also a 'photograph' page.
