### ISSUE TITLE
Feature request: Code block with filename

### ISSUE THREAD

**Issue by mrtnvgr** [isunjn/serene#24]
Commonmark [doesn't have these yet](https://talk.commonmark.org/t/code-blocks-extension-for-filenames-and-line-numbers/536/8). I think they can be implemented as shortcodes (like callouts?):
```
{% code(toml, name="config.toml" %}
[section]
value = "foo"
{% end %}

// or...

{% code(lang=toml, name="config.toml" %}
[section]
value = "foo"
{% end %}

```

**Comment by isunjn** [comment]
It's a feature nice to have, but I don't have a strong will to implement it myself. If you really need this, you can try to implement it yourself or wait for other people's pr.
