### ISSUE TITLE
Feature request: hide tags and page.summary

### ISSUE THREAD

**Issue by woojiq** [isunjn/serene#40]
Hi, first of all thanks for creating this theme, it looks great. Here are a few features I would like to see in this theme.

- [x] ~~Option to justify blog text. Iiuc this needs something like this https://github.com/rhazdon/hugo-theme-hello-friend-ng/issues/20#issuecomment-488144749.~~ **EDIT**: I don't need it anymore. I realized that I can `@import "../theme/serene/sass/main.scss"` so after updating serene I won't need to copy new css anymore.
- [ ] Option to hide tags even if they are present. I like to tag but not show. I can just comment them out in the markup, but if I have 20 posts and suddenly realize I want to show the tags, it's going to take a long time.
- [ ] Option to not include `page.summary` in a blog post. This will be useful if you want to add a summary for rss andwant to remove this text from the beginning of a post. In the future `page.summary` can be used under post name on the blog page.

**EDIT**: I've done it locally, waiting to hear from you if you want it in serene.

**Comment by isunjn** [comment]
- For 'justify', I agree to this post: <https://ruitina.com/dont-justify-text-on-websites-and-apps/> and will not add an option for that. 

- Add a `display_tags` would be nice, PR welcomed.

- I'm not following the idea of removing `page.summary`, could you explain it a bit more.

**Comment by woojiq** [comment]
> For 'justify', I agree to this post: https://ruitina.com/dont-justify-text-on-websites-and-apps/ and prefer not to add an option for that.

`text-align: justify` + `hyphens: auto;` looks not bad. I saw it on https://matklad.github.io/. Anyway, yea, it can be easily changed on client side.

> I'm not following the idea of removing page.summary, could you explain it a bit more.

I want to write descriptions for articles, but description will not be just the beginning of the article, but a short description of the entire article (summary). Therefore, it is not appropriate to show it at the beginning. At the same time, the description is useful for the rss feed and later it would be nice to show summary under post title on the blog page. For example look at the card generetaed by [openring](https://git.sr.ht/~sircmpwn/openring) 
![image](https://github.com/isunjn/serene/assets/122799969/c1e25b19-74e4-465f-8716-e1927a20399e)
and the article [itself](https://go.dev/blog/go1.21). As you can see, description is not included in the blog post. Hope you understand what I mean.

**Comment by isunjn** [comment]
Now I get it, this involves updating docs, I'm working on it.

For `display_tags`, seems trivial, open a pr if you want.
