### ISSUE TITLE
Feature Request: Fancy 404 page

### ISSUE THREAD

**Issue by mrtnvgr** [isunjn/serene#46]
Something minimal just like the home page would be nice :)

**Comment by isunjn** [comment]
sure. just wait for a while

**Comment by isunjn** [comment]
done

**Comment by bwo** [comment]
is the fancy homepage actually mandatory? it isn't mentioned in usage.md but I get a "Failed to render '404.html'" after switching to this theme

**Comment by isunjn** [comment]
@bwo it's not mandatory, you can delete `templates/404.html` or setup related config items in `config.toml`. check `config.example.toml`
