### ISSUE TITLE
Idea: Automatic demo deployment

### ISSUE THREAD

**Issue by mrtnvgr** [isunjn/serene#47]
You can create a github workflow which will deploy demo with the newest version of the theme (to Vercel, or Github Pages).

**Comment by isunjn** [comment]
I will take a look, but there may be breaking changes that need manual tweaks before build

**Comment by mrtnvgr** [comment]
> I will take a look, but there may be breaking changes that need manual tweaks before build

Forgot to mention that rebuilds should be run at version bumps, so only well-tested locally stuff will be published. I can make a PR if you don't mind.

**Comment by isunjn** [comment]
sure

**Comment by mrtnvgr** [comment]
Seems that something similar is already [implemented](https://github.com/isunjn/serene-demo-site/deployments). I think you should mention that repo somewhere here in docs.

**Comment by isunjn** [comment]
The demo site was deployed on vercel, triggered by a manual `git push`.

The idea of automatically triggered deployment at version bumps is actually not achievable, because it may involves copy new items from `config.example.toml` to `config.toml` (adding new config items is not a breaking change)
