### ISSUE TITLE
Help wanted: `zola serve` doesn't work

### ISSUE THREAD

**Issue by Seasawher** [isunjn/serene#48]
Hello. Thanks for making such a nice theme!

## my code

I thought I would clone your theme and create a blog. Here is the code.
https://github.com/Seasawher/serene-blog

## zola serve doesn't work

But `zola serve` does not work. I get an error that `highlight_themes` is not found.

In `config.toml`, you will find the following line

```toml
extra_syntaxes_and_themes = ["highlight_themes"]
````

If you change it as follows, it will work:

```toml
extra_syntaxes_and_themes = ["themes/serene/highlight_themes"]
```

However, I thought this might not be the design intended on the serene side. The reason is that zola's initial screen is displayed without the theme applied.

## my problem

In zola, I remember that when using a theme, it was sufficient to write a custom file in the templates directory only when you wanted to override the theme. However, for some reason, this does not seem to work on my blog.

After `zola serve`, I get an error that `github.svg` is not found. Of course, there is a `github.svg` under `themse/serene/`, but zola can't find it.

What on earth did I do wrong? I would appreciate any advice you can give me...

Thanks for reading.

**Comment by Seasawher** [comment]
Thank you! After copying `highlight_themes` and `static/icon`, the first error disappeared. 

However, I still get an error with `zola serve`. The error message is as follows.

```text
Error: Failed to serve the site
Error: Error parsing templates from the /templates directory
Error: Reason: Io error while writing rendered value to output: NotFound
Error: Reason: 指定されたファイルが見つかりません。 (os error 2)
```

The error message says that some files cannot be found, but which file is it?

My code is here: https://github.com/Seasawher/serene-blog

**Comment by isunjn** [comment]
create a /tempaltes folder

**Comment by Seasawher** [comment]
`zola serve` is now working properly. Thank you very much.
