### ISSUE TITLE
The URL of a Blog post is wrong in a page deployed to GitHub Pages

### ISSUE THREAD

**Issue by Seasawher** [isunjn/serene#50]
Thank you very much for your help earlier. 

`zola serve` is working perfectly. However, there is a problem when deploying it, even though it works well locally.

I deployed to GitHub Pages using GitHub Action, but I can't view the Blog post (404 error). Why does this happen?

here is my code: https://github.com/Seasawher/Seasawher.github.io

**Comment by isunjn** [comment]
you did't create the 'content/projects/_index.md' and 'content/projects/data.toml', so the projects link go to a 404 page.

please read the document throughly before submiting an issue

**Comment by Seasawher** [comment]
@isunjn 

Thanks for the reply. My problem was with the blog, not the project page.

But I just checked and it's fixed even though I didn't do anything, maybe when deploying with GitHub Action, you have to wait long enough to get the link to the correct link destination.
