### ISSUE TITLE
Issue with linenos + minify_html

### ISSUE THREAD

**Issue by dewa251202** [isunjn/serene#51]
Using code listing with `linenos` enabled, while `minify_html` is set to `true` in `config.toml`, will mess the layout.

Here's an example screenshot of this issue.
![image](https://github.com/isunjn/serene/assets/38946018/1ced04d0-f2ca-4204-99e9-77229a0ca004)

Demo site suffers the same.
![image](https://github.com/isunjn/serene/assets/38946018/649bb539-4d51-4c58-a135-659191295df4)

**Comment by dewa251202** [comment]
Oh, `minify_html` is a config from Zola, not from this theme. I guess you can close this issue.

**Comment by isunjn** [comment]
yes, seems like zola's `minify_html` will somehow break nesting structure of the page, it's not recommended
