### ISSUE TITLE
Include pagination for home page (list view) and blog page

### ISSUE THREAD

**Issue by prrao87** [isunjn/serene#54]
I love this theme! Thanks so much for creating it!

I'm noticing that if I enable `list` mode for the home page, the footer gets pushed way down and the list of posts goes on endlessly. Do you think it makes sense to think of including pagination, with the right UI elements in place for it? A lot of other themes do this.

I realize I could customize it and add shortcodes for it as per the Zola docs, but it would be awesome to have the right stylistic elements in place (e.g., arrow buttons) that align with the rest of the theme. Hope this makes sense!

**Comment by isunjn** [comment]
how many posts do you have?

personally i just don't like seeing a  personal-blog with pagination, i often jump to archive/timeline page directly if it has one :-)

i prefer a 'show more' button to prevent the list gets too long, it's once supported in this theme but now removed, for simplicity

**Comment by prrao87** [comment]
I have 15 blog posts and many more to come over the coming year. For the Archive page, I can understand. But for the home page I really like the list view and would like to show say 7-8 most recent posts there.

Would you be able to point me to how a "show more" button can be implemented? Just some sample code would be amazing.

**Comment by isunjn** [comment]
check [this commit](https://github.com/isunjn/serene/commit/2cdf475dd72bc58c9674f425b587015d3898807f)，might be helpful
