### ISSUE TITLE
Templates should use {{config.base_url}}

### ISSUE THREAD

**Issue by nathanielnrn** [isunjn/serene#55]
This template is lovely! Thanks for working on it. One thing I encountered when trying to deploy to a github pages _project_ page (as opposed to a user one, i.e `nathanielnrn.github.io/project` vs just `nathanielnrn.github.io`).

Templates should use {{config.base_url}} before things like `/js` and `/main.css` to ensure that deployment works when the base url is extended. (i.e `base_url = "mywebsite.com/extended"`)

Relevant for places like [here](https://github.com/isunjn/serene/blob/main/templates/_base.html#L16), [here](https://github.com/isunjn/serene/blob/main/templates/home.html#L52), and [here](https://github.com/isunjn/serene/blob/main/templates/prose.html#L14) to name a few.

**Comment by isunjn** [comment]
thanks, i will take a look

**Comment by isunjn** [comment]
> Templates should use {{config.base_url}} before things like /js and /main.css

this will make the request an absolute one, will cause problems at local previewing

also, for a 'personal blog site' it seems not reasonable to deploy it at a sub-path, so i prefer not to add this kind of support to the theme

if you realy need this, you can adjust it yourself
