### ISSUE TITLE
Giscus CORS

### ISSUE THREAD

**Issue by 0xlgtm** [isunjn/serene#56]
Hi, I have a CORS issue with giscus but I'm not really sure how to resolve it. I followed the instructions here https://github.com/isunjn/serene/blob/main/USAGE.md#comments.

![image](https://github.com/isunjn/serene/assets/17739166/52fe5719-ac21-485d-b3eb-6174a48d6888)

Any help would be appreciated!

**Comment by isunjn** [comment]
seems your site is hosted on netlify, you may check [this guide](https://answers.netlify.com/t/support-guide-handling-cors-on-netlify/107739)

**Comment by 0xlgtm** [comment]
From the guide shared by @isunjn , fixed it with

```
[[headers]]
  for = "/*"
  [headers.values]
    access-control-allow-origin = "https://giscus.app"
```

Thank you so much! 😄
