### ISSUE TITLE
Update to feed-related config keys.

### ISSUE THREAD

**Issue by masroof-maindak** [isunjn/serene#59]
Hi, thanks for the amazing theme, it's everything I've ever wanted from Hugo for a LONG while; one tiny thing I had to adjust to get it to work however was adding an `s` to instances of feed-related keys, namely `generate_feed` to `generate_feeds` and `feed_filename` to `feed_filenames` in **config.toml** as well as **content/blog/_index.md**. Additionally, the value of `feed_filenames` needs to be encased within an array.

Just thought I'd let you know in case you weren't aware.

**Comment by isunjn** [comment]
Thanks, this is due to a breaking change of zola v0.19.0 ([#2477](https://github.com/getzola/zola/pull/2477)), fixed in v4.0.0
