### ISSUE TITLE
mermaid 语法错误

### ISSUE THREAD

**Issue by silentbluedrop** [isunjn/serene#8]
不管页面的头部设置 mermaid = true，还是在 config.toml 文件中设置 mermaid = true 都会出现这个 mermaid 语法错误的图片。
![mermaid](https://user-images.githubusercontent.com/25808342/217525363-bfbcfc33-26eb-428c-98a1-dfd1ce05a3ee.png)

**Comment by isunjn** [comment]
语法错误与主题无关，你可以在检查下你mermaid图表的写法是否和mermaid官网的语法一致
（also sorry for the long waiting）
